# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [year/2025]
  pull_request:
    branches: [year/2025]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 24.x
      - run: npm ci
      - run: npm run build --if-present
      - run: touch dist/CNAME
      - run: echo "www.arvindsuresh.in" > dist/CNAME
      - name: Push git subdirectory as branch
        uses: s0/git-publish-subdir-action@v2.5.0
        env:
          REPO: self
          BRANCH: master
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.personal_token }}
